# Generated by Django 4.2.16 on 2024-10-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tabel_number',
            field=models.CharField(max_length=10),
        ),
    ]
