# Generated by Django 4.2.16 on 2024-10-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_tabel_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabel_number', models.CharField(max_length=10, unique=True, verbose_name='Табельный номер')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='tabel_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Табельный номер'),
        ),
    ]
