# Generated by Django 4.2.16 on 2024-11-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='weekdays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday_name', models.CharField(max_length=15, verbose_name='День недели')),
            ],
        ),
    ]
