# Generated by Django 4.2.16 on 2024-11-08 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_dish'),
    ]

    operations = [
        migrations.CreateModel(
            name='week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер недели')),
            ],
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.category'),
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.dish')),
                ('week_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.week')),
                ('weekday_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.weekday')),
            ],
        ),
    ]
