# Generated by Django 4.2.16 on 2024-11-08 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_week_alter_dish_category_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(verbose_name='Номер заказа')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('open', models.BooleanField(default=0, verbose_name='Заказ выполнен')),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.menu')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
