# Generated by Django 4.2.16 on 2024-11-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_menu_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.BigIntegerField(unique=True, verbose_name='Номер заказа'),
        ),
    ]
