# Generated by Django 4.2.16 on 2024-11-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_order_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='open',
            field=models.BooleanField(default=True, verbose_name='Заказ выполнен'),
        ),
    ]
