# Generated by Django 4.2.16 on 2024-11-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_order_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
    ]
