# Generated by Django 4.2.16 on 2024-11-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_dish_dish_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='open',
            field=models.BooleanField(default=True, verbose_name='Заказ открыт'),
        ),
    ]
