# Generated by Django 4.2.16 on 2024-11-27 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_order_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='app.city'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=25, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='table_number',
            name='tabel_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Табельный'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tabel_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Табельный'),
        ),
        migrations.AlterField(
            model_name='week',
            name='number',
            field=models.IntegerField(verbose_name='Неделя'),
        ),
        migrations.AlterField(
            model_name='weekday',
            name='weekday_name',
            field=models.CharField(max_length=15, verbose_name='День'),
        ),
    ]
