# Generated by Django 4.2.16 on 2024-11-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_user_city_alter_category_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.BigIntegerField(verbose_name='Номер заказа')),
                ('user_tabel_number', models.CharField(max_length=10, verbose_name='Табельный пользователя')),
                ('user_username', models.CharField(max_length=150, verbose_name='Имя пользователя')),
                ('dishes', models.TextField(blank=True, verbose_name='Блюда')),
                ('city_name', models.CharField(max_length=50, verbose_name='Город')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма заказа')),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
