# Generated by Django 4.2.16 on 2024-12-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_archivedorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedorder',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Paid'), (2, 'Closed'), (3, 'Expired')], default=3),
        ),
    ]
