# Generated by Django 4.2.16 on 2024-12-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_archivedorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedorder',
            name='order_number',
            field=models.BigIntegerField(unique=True, verbose_name='Номер заказа'),
        ),
    ]
