# Generated by Django 4.2.16 on 2024-12-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_archivedorder_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='open',
        ),
        migrations.AddField(
            model_name='user',
            name='blocked',
            field=models.BooleanField(default=False, verbose_name='Заблокирован'),
        ),
    ]
