# Generated by Django 4.2.16 on 2024-12-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_order_open_user_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedorder',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Оплачен на месте'), (2, 'Оплата из зарплаты'), (3, 'Просрочен')], default=3),
        ),
    ]
