# Generated by Django 4.2.16 on 2025-01-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_order_paid_user_balance_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Идентификатор платежа'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Пополнение'), ('withdrawal', 'Списание'), ('refund', 'Возврат')], max_length=10, verbose_name='Тип транзакции'),
        ),
    ]
