# Generated by Django 4.2.16 on 2025-01-15 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_transaction_payment_reference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
    ]
