# Generated by Django 4.2.16 on 2025-03-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_order_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedorder',
            name='city_name',
            field=models.CharField(max_length=50, verbose_name='Linn'),
        ),
        migrations.AlterField(
            model_name='archivedorder',
            name='dishes',
            field=models.TextField(blank=True, verbose_name='Roogad'),
        ),
        migrations.AlterField(
            model_name='archivedorder',
            name='order_number',
            field=models.BigIntegerField(unique=True, verbose_name='Tellimuse number'),
        ),
        migrations.AlterField(
            model_name='archivedorder',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Väljastatud'), (3, 'Aegunud')], default=3),
        ),
        migrations.AlterField(
            model_name='archivedorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tellimuse summa'),
        ),
        migrations.AlterField(
            model_name='archivedorder',
            name='user_tabel_number',
            field=models.CharField(max_length=10, verbose_name='Kasutaja tabelinumber'),
        ),
        migrations.AlterField(
            model_name='archivedorder',
            name='user_username',
            field=models.CharField(max_length=150, verbose_name='Kasutajanimi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=25, verbose_name='Kategooria'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Linn'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_name',
            field=models.CharField(max_length=50, verbose_name='Roog'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Hind'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.BigIntegerField(verbose_name='Tellimuse number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(verbose_name='Kogus'),
        ),
        migrations.AlterField(
            model_name='table_number',
            name='tabel_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Tabelinumber'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Summa'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tehingu kuupäev'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, verbose_name='Kirjeldus'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Makse identifikaator'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Täiendamine'), ('withdrawal', 'Vähendamine'), ('refund', 'Tagastus')], max_length=10, verbose_name='Tehingu tüüp'),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Saldo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='blocked',
            field=models.BooleanField(default=False, verbose_name='Blokeeritud'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tabel_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Tabelinumber'),
        ),
        migrations.AlterField(
            model_name='week',
            name='number',
            field=models.IntegerField(verbose_name='Nädal'),
        ),
        migrations.AlterField(
            model_name='weekday',
            name='weekday_name',
            field=models.CharField(max_length=15, verbose_name='Päev'),
        ),
    ]
