# Generated by Django 4.2.16 on 2025-03-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_archivedorder_city_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Sissemakse'), ('withdrawal', 'Väljamakse'), ('refund', 'Tagastus')], max_length=10, verbose_name='Tehingu tüüp'),
        ),
    ]
