# Generated by Django 4.2.16 on 2025-03-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tabel_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Töötaja number'),
        ),
    ]
