# app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('get_user_orders/', views.get_user_orders, name='get_user_orders'),
    path('dish/', views.dishes, name='dish'),
    path('operator/', views.operator, name='operator'),
    path('menu_page', views.menu_page, name='menu_page'),
    path('createmenu/', views.createmenu, name='createmenu'),
    path('replace_week_number/', views.replace_week_number, name='replace_week_number'),
    path('menu_view', views.menu_view, name='menu_view'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('submit_order/', views.submit_order, name='submit_order'),
    path('dish_del', views.dish_del, name='dish_del'),
    path('load-dishes/', views.load_dishes, name='load_dishes'),
    path('upd_menu', views.upd_menu, name='upd_menu'),
    path('', views.index, name='index'),
    path('orders/', views.orders, name='orders'),
    path('account/', views.account, name='account'),
    path('upd_user', views.upd_user, name='upd_user'),
    path('upd_pswd', views.upd_pswd, name='upd_pswd'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('check_tabel_number', views.check_tabel_number, name='check_tabel_number'),
    path('update_order_status/<int:order_number>/', views.update_order_status, name='update_order_status'),
    path('delete_order/<int:order_number>/', views.delete_order, name='delete_order'),
    path('dish/update/', views.dish_update, name='dish_update'),
    path('delete_menu_item/<int:menu_item_id>/', views.delete_menu_item, name='delete_menu_item'),
    path('get_dishes_by_category/<int:category_id>/', views.get_dishes_by_category, name='get_dishes_by_category'),
    path('update_menu_item/<int:id>/', views.update_menu_item, name='update_menu_item'),
    path('archive_order/', views.archive_order, name='archive_order'),
    path('send_receipt/<int:order_number>/', views.send_receipt, name='send_receipt'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html', 
                                                                email_template_name='registration/password_rst_email.html' ), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_rst_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_rst_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_rst_complete.html'), name='password_reset_complete'),
    path('service/', views.service, name='service'),
    path('order_archive', views.order_archive, name='order_archive'),
    path('run-archive-expired-orders/', views.run_archive_expired_orders, name='run_archive_expired_orders'),
    path('run-send-archived-orders-email/', views.run_send_archived_orders_email, name='run_send_archived_orders_email'),
    path('run-send-orders-email/', views.run_send_orders_email, name='run_send_orders_email'),
    path('run-tabel-number/', views.run_tabel_number, name='run-tabel-number'),
    path('initiate-payment/<int:user_id>/', views.initiate_payment, name='initiate_payment'),
    path('callback/', views.callback, name='callback'),
    path('balance/', views.balance, name='balance'),
    path('initiate-refund/<int:user_id>/', views.initiate_refund, name='initiate_refund'),
]